nombre= input("Ingrese su nombre:")
apellido= input("Ingrese su apellido:")
seccion= input("Ingrese su sección")
sede= input("Ingrese su sede:")
print("Nombre:", nombre)
print("Apellido:", apellido)
print("Seccion:", seccion)
print("Sede:", sede)